// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnqZZ-TEzWjuvljSLIqieRAUX2tV28nM',
    appId: '1:639627000241:android:18c2c2e076ca373a1da590',
    messagingSenderId: '639627000241',
    projectId: 'kakoa-f7fe6',
    storageBucket: 'kakoa-f7fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF45MZl4UPaR6VhE1Fmi5TV1uU2oplko4',
    appId: '1:639627000241:ios:374a5f48900127181da590',
    messagingSenderId: '639627000241',
    projectId: 'kakoa-f7fe6',
    storageBucket: 'kakoa-f7fe6.appspot.com',
    androidClientId: '639627000241-pdkietejq22dim1nvr9egi1obea1ctc7.apps.googleusercontent.com',
    iosClientId: '639627000241-igdldqq5dnvaa6ggetr4b83u7glc2df6.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpark',
  );
}
